# Generated by Django 4.2.16 on 2025-11-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_allauth_migration_order'),
        ('account', '0001_initial'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        # This migration ensures that all django-allauth migrations are properly
        # dependent on our custom accounts app migrations.
        #
        # This resolves the InconsistentMigrationHistory error:
        # "Migration account.0001_initial is applied before its dependency accounts.0001_initial"
        migrations.RunSQL("SELECT 1;")  # No-op migration
    ]