# Generated by Django 4.2.16 on 2025-11-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_account_dependency'),
    ]

    operations = [
        # This migration exists to further ensure proper dependency ordering
        # between the custom accounts app and django-allauth account app.
        # It's an additional safeguard against InconsistentMigrationHistory errors.
        migrations.RunSQL("SELECT 1;")  # No-op migration
    ]