# Generated by Django 4.2.16 on 2025-11-24 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numerology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('basic', 'Basic Birth Chart'), ('detailed', 'Detailed Analysis'), ('compatibility', 'Compatibility Report'), ('career', 'Career Guidance'), ('relationship', 'Relationship Analysis'), ('health', 'Health Insights'), ('finance', 'Financial Forecast'), ('yearly', 'Yearly Forecast'), ('monthly', 'Monthly Guidance'), ('daily', 'Daily Reading')], max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['report_type', 'is_active'], name='report_temp_report__fe6a31_idx'), models.Index(fields=['is_premium'], name='report_temp_is_prem_87d0cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='numerology.person')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'generated_reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'generated_at'], name='generated_r_user_id_33f950_idx'), models.Index(fields=['person', 'template'], name='generated_r_person__455f5f_idx')],
            },
        ),
    ]
