# Generated by Django 4.2.16 on 2025-11-24 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialty', models.CharField(choices=[('relationship', 'Relationship & Compatibility'), ('career', 'Career & Business'), ('spiritual', 'Spiritual Growth'), ('health', 'Health & Wellness'), ('general', 'General Numerology')], max_length=20)),
                ('experience_years', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('bio', models.TextField()),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
                'db_table': 'experts',
                'ordering': ['-rating', '-experience_years'],
                'indexes': [models.Index(fields=['specialty', 'is_active'], name='experts_special_61ffdd_idx'), models.Index(fields=['rating'], name='experts_rating_47b7e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_type', models.CharField(choices=[('video', 'Video Call'), ('chat', 'Chat'), ('phone', 'Phone Call')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultations.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Consultation Review',
                'verbose_name_plural': 'Consultation Reviews',
                'db_table': 'consultation_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultation'], name='consultatio_consult_83762f_idx'), models.Index(fields=['rating'], name='consultatio_rating_8fcb28_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['user', 'scheduled_at'], name='consultatio_user_id_68d40d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['expert', 'scheduled_at'], name='consultatio_expert__73f6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='consultatio_status_beb187_idx'),
        ),
    ]
