# Generated by Django 4.2.16 on 2025-11-24 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('partner', 'Business Partner'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remedy_type', models.CharField(choices=[('gemstone', 'Gemstone'), ('color', 'Color'), ('ritual', 'Ritual'), ('mantra', 'Mantra'), ('dietary', 'Dietary'), ('exercise', 'Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remedy',
                'verbose_name_plural': 'Remedies',
                'db_table': 'remedies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonNumerologyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('life_path_number', models.IntegerField()),
                ('destiny_number', models.IntegerField()),
                ('soul_urge_number', models.IntegerField()),
                ('personality_number', models.IntegerField()),
                ('attitude_number', models.IntegerField()),
                ('maturity_number', models.IntegerField()),
                ('balance_number', models.IntegerField()),
                ('personal_year_number', models.IntegerField()),
                ('personal_month_number', models.IntegerField()),
                ('calculation_system', models.CharField(choices=[('pythagorean', 'Pythagorean'), ('chaldean', 'Chaldean')], default='pythagorean', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numerology_profile', to='numerology.person')),
            ],
            options={
                'verbose_name': 'Person Numerology Profile',
                'verbose_name_plural': 'Person Numerology Profiles',
                'db_table': 'person_numerology_profiles',
            },
        ),
        migrations.CreateModel(
            name='NumerologyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('life_path_number', models.IntegerField()),
                ('destiny_number', models.IntegerField()),
                ('soul_urge_number', models.IntegerField()),
                ('personality_number', models.IntegerField()),
                ('attitude_number', models.IntegerField()),
                ('maturity_number', models.IntegerField()),
                ('balance_number', models.IntegerField()),
                ('personal_year_number', models.IntegerField()),
                ('personal_month_number', models.IntegerField()),
                ('karmic_debt_number', models.IntegerField(blank=True, null=True)),
                ('hidden_passion_number', models.IntegerField(blank=True, null=True)),
                ('subconscious_self_number', models.IntegerField(blank=True, null=True)),
                ('calculation_system', models.CharField(choices=[('pythagorean', 'Pythagorean'), ('chaldean', 'Chaldean')], default='pythagorean', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numerology_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Numerology Profile',
                'verbose_name_plural': 'Numerology Profiles',
                'db_table': 'numerology_profiles',
            },
        ),
        migrations.CreateModel(
            name='DailyReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_date', models.DateField(db_index=True)),
                ('personal_day_number', models.IntegerField()),
                ('lucky_number', models.IntegerField()),
                ('lucky_color', models.CharField(max_length=50)),
                ('auspicious_time', models.CharField(max_length=50)),
                ('activity_recommendation', models.TextField()),
                ('warning', models.TextField()),
                ('affirmation', models.TextField()),
                ('actionable_tip', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Reading',
                'verbose_name_plural': 'Daily Readings',
                'db_table': 'daily_readings',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_birth_date', models.DateField()),
                ('relationship_type', models.CharField(choices=[('romantic', 'Romantic'), ('business', 'Business'), ('friendship', 'Friendship'), ('family', 'Family')], max_length=20)),
                ('compatibility_score', models.IntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('challenges', models.JSONField(default=list)),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compatibility Check',
                'verbose_name_plural': 'Compatibility Checks',
                'db_table': 'compatibility_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemedyTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='numerology.remedy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remedy Tracking',
                'verbose_name_plural': 'Remedy Trackings',
                'db_table': 'remedy_trackings',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='remedy_trac_user_id_d27392_idx'), models.Index(fields=['remedy', 'date'], name='remedy_trac_remedy__aef8b5_idx')],
                'unique_together': {('user', 'remedy', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='remedy',
            index=models.Index(fields=['user', 'remedy_type'], name='remedies_user_id_136d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='remedy',
            index=models.Index(fields=['is_active'], name='remedies_is_acti_41f20b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'is_active'], name='people_user_id_ed3efb_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['relationship'], name='people_relatio_09226c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('user', 'name', 'birth_date')},
        ),
        migrations.AddIndex(
            model_name='dailyreading',
            index=models.Index(fields=['user', 'reading_date'], name='daily_readi_user_id_ed83d9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreading',
            index=models.Index(fields=['reading_date'], name='daily_readi_reading_903981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreading',
            unique_together={('user', 'reading_date')},
        ),
        migrations.AddIndex(
            model_name='compatibilitycheck',
            index=models.Index(fields=['user', 'created_at'], name='compatibili_user_id_cae1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitycheck',
            index=models.Index(fields=['relationship_type'], name='compatibili_relatio_cd3cc4_idx'),
        ),
    ]
